import { OpenAPIV3 } from "openapi-types"
import { apiTitle, apiVersion, apiDescription, openApiVersion } from "../index"

const baseUrl = process.env.NEXT_PUBLIC_APP_URL || "http://localhost:3000"

export const openApiDocument: OpenAPIV3.Document = {
  openapi: openApiVersion,
  info: {
    title: apiTitle,
    version: apiVersion,
    description: apiDescription,
    contact: {
      name: "Soporte HC Gestor",
      email: "soporte@hcgestor.com",
    },
    license: {
      name: "Propietario",
      url: "https://hcgestor.com",
    },
  },
  servers: [
    {
      url: baseUrl,
      description: "Servidor de desarrollo",
    },
  ],
  components: {
    securitySchemes: {
      cookieAuth: {
        type: "apiKey",
        in: "cookie",
        name: "better-auth.session_token",
        description: "Cookie de sesión de Better Auth",
      },
    },
    schemas: {
      Error: {
        type: "object",
        properties: {
          error: { type: "string", description: "Mensaje de error" },
          details: { type: "string", description: "Detalles adicionales" },
        },
        required: ["error"],
      },
      Patient: {
        type: "object",
        properties: {
          id: { type: "string", description: "ID único del paciente" },
          firstName: { type: "string", description: "Nombre(s)" },
          lastName: { type: "string", description: "Apellido(s)" },
          middleName: { type: "string", description: "Segundo nombre" },
          curp: { type: "string", description: "CURP (solo México)" },
          birthDate: { type: "string", format: "date", description: "Fecha de nacimiento" },
          gender: { type: "string", enum: ["MALE", "FEMALE", "OTHER"], description: "Género" },
          bloodType: { type: "string", enum: ["A_POSITIVE", "A_NEGATIVE", "B_POSITIVE", "B_NEGATIVE", "AB_POSITIVE", "AB_NEGATIVE", "O_POSITIVE", "O_NEGATIVE"], description: "Tipo de sangre" },
          email: { type: "string", format: "email", description: "Correo electrónico" },
          phone: { type: "string", description: "Teléfono fijo" },
          mobile: { type: "string", description: "Teléfono móvil" },
          address: { type: "string", description: "Dirección" },
          city: { type: "string", description: "Ciudad" },
          state: { type: "string", description: "Estado" },
          zipCode: { type: "string", description: "Código postal" },
          photoUrl: { type: "string", description: "URL de foto" },
          isActive: { type: "boolean", description: "Activo/Inactivo" },
          createdAt: { type: "string", format: "date-time", description: "Fecha de creación" },
          updatedAt: { type: "string", format: "date-time", description: "Fecha de actualización" },
        },
        required: ["firstName", "lastName", "birthDate", "gender"],
      },
      PatientInput: {
        type: "object",
        properties: {
          firstName: { type: "string", minLength: 2, description: "Nombre(s)" },
          lastName: { type: "string", minLength: 2, description: "Apellido(s)" },
          middleName: { type: "string", description: "Segundo nombre" },
          curp: { type: "string", description: "CURP (formato: XXXX010101HNEXXXA1)" },
          birthDate: { type: "string", format: "date", description: "Fecha de nacimiento (YYYY-MM-DD)" },
          gender: { type: "string", enum: ["MALE", "FEMALE", "OTHER"], description: "Género" },
          bloodType: { type: "string", enum: ["A_POSITIVE", "A_NEGATIVE", "B_POSITIVE", "B_NEGATIVE", "AB_POSITIVE", "AB_NEGATIVE", "O_POSITIVE", "O_NEGATIVE"], description: "Tipo de sangre" },
          email: { type: "string", format: "email", description: "Correo electrónico" },
          phone: { type: "string", description: "Teléfono fijo" },
          mobile: { type: "string", description: "Teléfono móvil" },
          address: { type: "string", description: "Dirección" },
          city: { type: "string", description: "Ciudad" },
          state: { type: "string", description: "Estado" },
          zipCode: { type: "string", description: "Código postal" },
          notes: { type: "string", description: "Notas adicionales" },
        },
        required: ["firstName", "lastName", "birthDate", "gender"],
      },
      Appointment: {
        type: "object",
        properties: {
          id: { type: "string", description: "ID único de la cita" },
          patientId: { type: "string", description: "ID del paciente" },
          doctorId: { type: "string", description: "ID del doctor" },
          startTime: { type: "string", format: "date-time", description: "Fecha y hora de inicio" },
          endTime: { type: "string", format: "date-time", description: "Fecha y hora de fin" },
          status: { type: "string", enum: ["SCHEDULED", "CONFIRMED", "IN_PROGRESS", "COMPLETED", "CANCELLED", "NO_SHOW"], description: "Estado de la cita" },
          reason: { type: "string", description: "Motivo de la consulta" },
          notes: { type: "string", description: "Notas adicionales" },
          createdAt: { type: "string", format: "date-time" },
          updatedAt: { type: "string", format: "date-time" },
          patient: { $ref: "#/components/schemas/PatientSummary" },
          doctor: { $ref: "#/components/schemas/UserSummary" },
        },
        required: ["patientId", "doctorId", "startTime", "endTime", "status"],
      },
      AppointmentInput: {
        type: "object",
        properties: {
          patientId: { type: "string", description: "ID del paciente" },
          doctorId: { type: "string", description: "ID del doctor" },
          startTime: { type: "string", format: "date-time", description: "Fecha y hora de inicio (ISO 8601)" },
          endTime: { type: "string", format: "date-time", description: "Fecha y hora de fin (ISO 8601)" },
          status: { type: "string", enum: ["SCHEDULED", "CONFIRMED", "IN_PROGRESS", "COMPLETED", "CANCELLED", "NO_SHOW"], description: "Estado de la cita" },
          reason: { type: "string", description: "Motivo de la consulta" },
          notes: { type: "string", description: "Notas adicionales" },
        },
        required: ["patientId", "doctorId", "startTime", "endTime"],
      },
      AppointmentUpdate: {
        type: "object",
        properties: {
          patientId: { type: "string" },
          doctorId: { type: "string" },
          startTime: { type: "string", format: "date-time" },
          endTime: { type: "string", format: "date-time" },
          status: { type: "string", enum: ["SCHEDULED", "CONFIRMED", "IN_PROGRESS", "COMPLETED", "CANCELLED", "NO_SHOW"] },
          reason: { type: "string" },
          notes: { type: "string" },
        },
      },
      MedicalNote: {
        type: "object",
        properties: {
          id: { type: "string" },
          appointmentId: { type: "string" },
          patientId: { type: "string" },
          doctorId: { type: "string" },
          subjective: { type: "string", description: "Subjetivo (S del SOAP)" },
          objective: { type: "string", description: "Objetivo (O del SOAP)" },
          assessment: { type: "string", description: "Evaluación (A del SOAP)" },
          plan: { type: "string", description: "Plan (P del SOAP)" },
          diagnosis: { type: "string", description: "Diagnóstico principal" },
          icdCode: { type: "string", description: "Código ICD-10" },
          vitalSigns: { $ref: "#/components/schemas/VitalSigns" },
          attachments: { type: "array", items: { type: "string" }, description: "URLs de archivos adjuntos" },
          createdAt: { type: "string", format: "date-time" },
          updatedAt: { type: "string", format: "date-time" },
        },
        required: ["appointmentId", "patientId", "doctorId"],
      },
      MedicalNoteInput: {
        type: "object",
        properties: {
          appointmentId: { type: "string" },
          patientId: { type: "string" },
          doctorId: { type: "string" },
          subjective: { type: "string" },
          objective: { type: "string" },
          assessment: { type: "string" },
          plan: { type: "string" },
          diagnosis: { type: "string" },
          icdCode: { type: "string" },
          vitalSigns: { $ref: "#/components/schemas/VitalSignsInput" },
        },
        required: ["appointmentId", "patientId", "doctorId"],
      },
      VitalSigns: {
        type: "object",
        properties: {
          bloodPressureSystolic: { type: "number", description: "Presión sistólica (mmHg)" },
          bloodPressureDiastolic: { type: "number", description: "Presión diastólica (mmHg)" },
          heartRate: { type: "number", description: "Frecuencia cardíaca (lpm)" },
          temperature: { type: "number", description: "Temperatura (°C)" },
          weight: { type: "number", description: "Peso (kg)" },
          height: { type: "number", description: "Altura (cm)" },
          bmi: { type: "number", description: "Índice de masa corporal" },
          oxygenSaturation: { type: "number", description: "Saturación de oxígeno (%)" },
          glucose: { type: "number", description: "Glucosa (mg/dL)" },
        },
      },
      VitalSignsInput: {
        type: "object",
        properties: {
          bloodPressureSystolic: { type: "number", minimum: 50, maximum: 250 },
          bloodPressureDiastolic: { type: "number", minimum: 30, maximum: 150 },
          heartRate: { type: "number", minimum: 30, maximum: 200 },
          temperature: { type: "number", minimum: 30, maximum: 45 },
          weight: { type: "number", minimum: 1, maximum: 500 },
          height: { type: "number", minimum: 30, maximum: 300 },
          bmi: { type: "number" },
          oxygenSaturation: { type: "number", minimum: 50, maximum: 100 },
          glucose: { type: "number", minimum: 20, maximum: 600 },
        },
      },
      Prescription: {
        type: "object",
        properties: {
          id: { type: "string" },
          patientId: { type: "string" },
          doctorId: { type: "string" },
          appointmentId: { type: "string" },
          medications: { type: "array", items: { $ref: "#/components/schemas/Medication" } },
          instructions: { type: "string", description: "Instrucciones generales" },
          validDays: { type: "number", description: "Días de validez" },
          signature: { type: "string", description: "Firma digital del médico" },
          pdfUrl: { type: "string", description: "URL del PDF generado" },
          createdAt: { type: "string", format: "date-time" },
          updatedAt: { type: "string", format: "date-time" },
        },
        required: ["patientId", "doctorId", "medications"],
      },
      PrescriptionInput: {
        type: "object",
        properties: {
          patientId: { type: "string" },
          doctorId: { type: "string" },
          appointmentId: { type: "string" },
          medications: { type: "array", items: { $ref: "#/components/schemas/MedicationInput" } },
          instructions: { type: "string" },
          validDays: { type: "number", default: 30 },
        },
        required: ["patientId", "doctorId", "medications"],
      },
      Medication: {
        type: "object",
        properties: {
          name: { type: "string", description: "Nombre del medicamento" },
          dosage: { type: "string", description: "Dosis (ej: 500mg)" },
          frequency: { type: "string", description: "Frecuencia (ej: cada 8 horas)" },
          duration: { type: "string", description: "Duración (ej: 7 días)" },
          route: { type: "string", enum: ["ORAL", "TOPICAL", "INTRAMUSCULAR", "INTRAVENOUS", "SUBCUTANEOUS", "INHALED", "RECTAL", "SUBLINGUAL", "OTHER"], description: "Vía de administración" },
          instructions: { type: "string", description: "Instrucciones específicas" },
          quantity: { type: "number", description: "Cantidad" },
          refills: { type: "number", description: "Reposiciones" },
        },
        required: ["name", "dosage", "frequency", "route"],
      },
      MedicationInput: {
        type: "object",
        properties: {
          name: { type: "string" },
          dosage: { type: "string" },
          frequency: { type: "string" },
          duration: { type: "string" },
          route: { type: "string", enum: ["ORAL", "TOPICAL", "INTRAMUSCULAR", "INTRAVENOUS", "SUBCUTANEOUS", "INHALED", "RECTAL", "SUBLINGUAL", "OTHER"] },
          instructions: { type: "string" },
          quantity: { type: "number" },
          refills: { type: "number" },
        },
        required: ["name", "dosage", "frequency", "route"],
      },
      LabOrder: {
        type: "object",
        properties: {
          id: { type: "string" },
          patientId: { type: "string" },
          doctorId: { type: "string" },
          appointmentId: { type: "string" },
          tests: { type: "array", items: { type: "string" }, description: "Lista de estudios" },
          priority: { type: "string", enum: ["ROUTINE", "URGENT", "STAT"], description: "Prioridad" },
          status: { type: "string", enum: ["PENDING", "COLLECTED", "IN_PROGRESS", "COMPLETED", "CANCELLED"], description: "Estado" },
          clinicalNotes: { type: "string", description: "Notas clínicas" },
          results: { type: "object", description: "Resultados del laboratorio" },
          resultReleasedAt: { type: "string", format: "date-time", description: "Fecha de liberación de resultados" },
          pdfUrl: { type: "string", description: "URL del PDF" },
          createdAt: { type: "string", format: "date-time" },
          updatedAt: { type: "string", format: "date-time" },
        },
        required: ["patientId", "doctorId", "tests"],
      },
      LabOrderInput: {
        type: "object",
        properties: {
          patientId: { type: "string" },
          doctorId: { type: "string" },
          appointmentId: { type: "string" },
          tests: { type: "array", items: { type: "string" } },
          priority: { type: "string", enum: ["ROUTINE", "URGENT", "STAT"], default: "ROUTINE" },
          clinicalNotes: { type: "string" },
        },
        required: ["patientId", "doctorId", "tests"],
      },
      ImagingOrder: {
        type: "object",
        properties: {
          id: { type: "string" },
          patientId: { type: "string" },
          doctorId: { type: "string" },
          appointmentId: { type: "string" },
          studyType: { type: "string", enum: ["XRAY", "ULTRASOUND", "CT", "MRI", "MAMMOGRAPHY", "BONE_DENSITY", "OTHER"], description: "Tipo de estudio" },
          description: { type: "string", description: "Descripción del estudio" },
          priority: { type: "string", enum: ["ROUTINE", "URGENT", "STAT"] },
          status: { type: "string", enum: ["PENDING", "SCHEDULED", "IN_PROGRESS", "COMPLETED", "CANCELLED"] },
          clinicalNotes: { type: "string" },
          findings: { type: "string", description: "Hallazgos" },
          impression: { type: "string", description: "Impresión/Conclusión" },
          pdfUrl: { type: "string" },
          dicomUrl: { type: "string", description: "URL DICOM" },
          completedAt: { type: "string", format: "date-time" },
          createdAt: { type: "string", format: "date-time" },
          updatedAt: { type: "string", format: "date-time" },
        },
        required: ["patientId", "doctorId", "studyType", "description"],
      },
      ImagingOrderInput: {
        type: "object",
        properties: {
          patientId: { type: "string" },
          doctorId: { type: "string" },
          appointmentId: { type: "string" },
          studyType: { type: "string", enum: ["XRAY", "ULTRASOUND", "CT", "MRI", "MAMMOGRAPHY", "BONE_DENSITY", "OTHER"] },
          description: { type: "string" },
          priority: { type: "string", enum: ["ROUTINE", "URGENT", "STAT"], default: "ROUTINE" },
          clinicalNotes: { type: "string" },
        },
        required: ["patientId", "doctorId", "studyType", "description"],
      },
      Invoice: {
        type: "object",
        properties: {
          id: { type: "string" },
          clinicId: { type: "string" },
          patientId: { type: "string" },
          invoiceNumber: { type: "string", description: "Número de factura" },
          serie: { type: "string", description: "Serie (ej: A)" },
          subtotal: { type: "number", description: "Subtotal" },
          tax: { type: "number", description: "Impuesto (16% IVA)" },
          total: { type: "number", description: "Total" },
          status: { type: "string", enum: ["DRAFT", "ISSued", "PAID", "CANCELLED", "REFUNDED"], description: "Estado" },
          issueDate: { type: "string", format: "date", description: "Fecha de emisión" },
          dueDate: { type: "string", format: "date", description: "Fecha de vencimiento" },
          items: { type: "array", items: { $ref: "#/components/schemas/InvoiceItem" } },
          payments: { type: "array", items: { $ref: "#/components/schemas/Payment" } },
          cfdiUuid: { type: "string", description: "UUID del CFDI timbrado" },
          pdfUrl: { type: "string", description: "URL del PDF" },
          xmlUrl: { type: "string", description: "URL del XML CFDI" },
          createdAt: { type: "string", format: "date-time" },
          updatedAt: { type: "string", format: "date-time" },
        },
        required: ["patientId", "items"],
      },
      InvoiceInput: {
        type: "object",
        properties: {
          patientId: { type: "string" },
          serie: { type: "string", default: "A" },
          items: { type: "array", items: { $ref: "#/components/schemas/InvoiceItemInput" } },
          issueDate: { type: "string", format: "date" },
          dueDate: { type: "string", format: "date" },
          notes: { type: "string" },
        },
        required: ["patientId", "items"],
      },
      InvoiceItem: {
        type: "object",
        properties: {
          id: { type: "string" },
          description: { type: "string", description: "Descripción del servicio" },
          quantity: { type: "number" },
          unitPrice: { type: "number" },
          subtotal: { type: "number" },
          tax: { type: "number" },
          total: { type: "number" },
          serviceId: { type: "string", description: "ID del servicio (si aplica)" },
        },
        required: ["description", "quantity", "unitPrice"],
      },
      InvoiceItemInput: {
        type: "object",
        properties: {
          description: { type: "string" },
          quantity: { type: "number", minimum: 1 },
          unitPrice: { type: "number", minimum: 0 },
          serviceId: { type: "string" },
        },
        required: ["description", "quantity", "unitPrice"],
      },
      Payment: {
        type: "object",
        properties: {
          id: { type: "string" },
          invoiceId: { type: "string" },
          amount: { type: "number" },
          method: { type: "string", enum: ["CASH", "CARD", "TRANSFER", "CHECK", "OTHER"], description: "Método de pago" },
          reference: { type: "string", description: "Referencia del pago" },
          status: { type: "string", enum: ["PENDING", "COMPLETED", "FAILED", "REFUNDED"] },
          paidAt: { type: "string", format: "date-time" },
          createdAt: { type: "string", format: "date-time" },
        },
        required: ["invoiceId", "amount", "method"],
      },
      PaymentInput: {
        type: "object",
        properties: {
          invoiceId: { type: "string" },
          amount: { type: "number", minimum: 0 },
          method: { type: "string", enum: ["CASH", "CARD", "TRANSFER", "CHECK", "OTHER"] },
          reference: { type: "string" },
        },
        required: ["invoiceId", "amount", "method"],
      },
      UserSummary: {
        type: "object",
        properties: {
          id: { type: "string" },
          name: { type: "string" },
          email: { type: "string" },
          specialty: { type: "string" },
          licenseNumber: { type: "string" },
        },
      },
      PatientSummary: {
        type: "object",
        properties: {
          id: { type: "string" },
          firstName: { type: "string" },
          lastName: { type: "string" },
          email: { type: "string" },
          phone: { type: "string" },
        },
      },
      Clinic: {
        type: "object",
        properties: {
          id: { type: "string" },
          name: { type: "string" },
          rfc: { type: "string", description: "RFC (México)" },
          email: { type: "string" },
          phone: { type: "string" },
          address: { type: "string" },
          logoUrl: { type: "string" },
        },
        required: ["name", "rfc"],
      },
      ClinicInput: {
        type: "object",
        properties: {
          name: { type: "string" },
          rfc: { type: "string" },
          email: { type: "string" },
          phone: { type: "string" },
          address: { type: "string" },
        },
        required: ["name", "rfc"],
      },
      DashboardStats: {
        type: "object",
        properties: {
          totalPatients: { type: "number" },
          appointmentsToday: { type: "number" },
          totalMedicalNotes: { type: "number" },
          monthlyRevenue: { type: "number", description: "Ingresos del mes en centavos" },
          pendingAppointments: { type: "number" },
        },
      },
    },
    responses: {
      BadRequest: {
        description: "Solicitud inválida",
        content: {
          "application/json": {
            schema: { $ref: "#/components/schemas/Error" },
            example: { error: "Validation error", details: "Email inválido" },
          },
        },
      },
      Unauthorized: {
        description: "No autorizado",
        content: {
          "application/json": {
            schema: { $ref: "#/components/schemas/Error" },
            example: { error: "Unauthorized" },
          },
        },
      },
      Forbidden: {
        description: "Acceso denegado",
        content: {
          "application/json": {
            schema: { $ref: "#/components/schemas/Error" },
            example: { error: "Forbidden" },
          },
        },
      },
      NotFound: {
        description: "Recurso no encontrado",
        content: {
          "application/json": {
            schema: { $ref: "#/components/schemas/Error" },
            example: { error: "Not found" },
          },
        },
      },
      InternalServerError: {
        description: "Error interno del servidor",
        content: {
          "application/json": {
            schema: { $ref: "#/components/schemas/Error" },
            example: { error: "Internal server error" },
          },
        },
      },
    },
  },
  security: [{ cookieAuth: [] }],
  paths: {},
}

export default openApiDocument
